# Auto-generated by generate_timeline.py
dialogue = [
    (0.05, 'speaker1', 2.7),
    (1.05, 'speaker3', 2.5),
    (2.05, 'speaker2', 2.5),
    (6.8, 'speaker1', 2.7),
    (8.55, 'speaker3', 2.5),
    (10.6, 'speaker2', 2.5),
    (17.55, 'speaker1', 2.45),
]
